use_frameworks!

platform :ios, '9.0'

target 'MGADENSDK_Example' do
  pod 'MGADENSDK', :path => '../'
  pod 'Google-Mobile-Ads-SDK', '=7.55.1'
  pod 'FBAudienceNetwork', '=5.7.0'
  pod 'GoogleMobileAdsMediationFacebook', '=5.7.0'
    
end

target 'MGADENSDK' do
  pod 'Google-Mobile-Ads-SDK', '=7.55.1'
  pod 'FBAudienceNetwork', '=5.7.0'
  pod 'GoogleMobileAdsMediationFacebook', '=5.7.0'

end
